import {
  Apple,
  Beef,
  Coffee,
  Cookie,
  Croissant,
  CupSoda,
  Fish,
  Gift,
  Leaf,
  Milk,
  PartyPopper,
  Pill,
  Salad,
  Shirt,
  ShoppingBag,
  Soup,
  Utensils,
  Wine,
} from 'lucide-react';

export const CATEGORIES = [
  {
    id: 'newyear',
    label: '새해설선물',
    icon: Gift,
    isNew: true,
    subcategories: [
      '건강식품 선물',
      '과일·정육 선물',
      '수산·건어물 선물',
      '베이커리·간식 선물',
      '생활용품 선물',
    ],
  },
  {
    id: 'festa',
    label: '리빙컬리페스타',
    icon: PartyPopper,
    isNew: true,
    subcategories: ['주방용품 특가', '생활용품 특가', '가전제품 특가'],
  },
  {
    id: 'duffle',
    label: '더퍼플셀렉션',
    icon: ShoppingBag,
    subcategories: ['더퍼플 단독', '프리미엄관'],
  },
  {
    id: 'veg',
    label: '채소',
    icon: Leaf,
    subcategories: [
      '친환경',
      '고구마·감자·당근',
      '시금치·쌈채소·나물',
      '브로콜리·파프리카·양배추',
      '양파·대파·마늘·배추',
      '오이·호박·고추',
      '콩나물·버섯',
    ],
  },
  {
    id: 'fruit',
    label: '과일·견과·쌀',
    icon: Apple,
    subcategories: [
      '친환경',
      '제철과일',
      '국산과일',
      '수입과일',
      '간편과일',
      '냉동·건과일',
      '견과류',
      '쌀·잡곡',
    ],
  },
  {
    id: 'seafood',
    label: '수산·해산·건어물',
    icon: Fish,
    subcategories: [
      '제철수산',
      '생선류',
      '오징어·낙지·문어',
      '새우·게·랍스터',
      '해산물·조개류',
      '김·미역·해조류',
      '건어물·다시팩',
    ],
  },
  {
    id: 'meat',
    label: '정육·가공육·달걀',
    icon: Beef,
    subcategories: [
      '국내산 소고기',
      '수입산 소고기',
      '돼지고기',
      '닭·오리고기',
      '양념육·돈까스',
      '계란류',
    ],
  },
  {
    id: 'soup',
    label: '국·반찬·메인요리',
    icon: Soup,
    subcategories: ['국·탕·찌개', '밀키트·메인요리', '밑반찬', '김치·젓갈·장류'],
  },
  {
    id: 'salad',
    label: '간편식·밀키트·샐러드',
    icon: Salad,
    subcategories: ['샐러드·닭가슴살', '도시락·밥류', '파스타·면류', '떡볶이·튀김·순대'],
  },
  {
    id: 'oil',
    label: '면·양념·오일',
    icon: Utensils,
    subcategories: ['파스타·면류', '식초·소스·드레싱', '오일·참기름', '소금·설탕·향신료'],
  },
  {
    id: 'water',
    label: '생수·음료',
    icon: CupSoda,
    subcategories: ['생수·탄산수', '음료·주스', '우유·두유·요거트'],
  },
  {
    id: 'coffee',
    label: '커피·차',
    icon: Coffee,
    subcategories: ['원두커피', '캡슐커피', '차류', '커피용품'],
  },
  {
    id: 'snack',
    label: '간식·과자·떡',
    icon: Cookie,
    subcategories: ['과자·스낵', '쿠키·파이', '초콜릿·젤리', '떡·한과'],
  },
  {
    id: 'bakery',
    label: '베이커리',
    icon: Croissant,
    subcategories: ['식빵·빵류', '잼·버터·스프레드', '케이크·디저트'],
  },
  {
    id: 'milk',
    label: '유제품',
    icon: Milk,
    subcategories: ['우유', '치즈', '버터·크림', '요거트'],
  },
  {
    id: 'health',
    label: '건강식품',
    icon: Pill,
    subcategories: ['홍삼·인삼', '유산균', '비타민·미네랄', '건강즙·액기스'],
  },
  {
    id: 'wine',
    label: '와인·위스키·데낄라',
    icon: Wine,
    isNew: true,
    subcategories: ['레드와인', '화이트와인', '스파클링와인', '위스키', '리큐르'],
  },
  {
    id: 'trad',
    label: '전통주',
    icon: Shirt,
    subcategories: ['막걸리·탁주', '증류주', '약주·청주', '과실주'],
  },
  {
    id: 'fashion',
    label: '패션',
    icon: Shirt,
    subcategories: ['여성의류', '남성의류', '잡화', '쥬얼리'],
  },
];

export const PRODUCTS = [
  {
    id: 1,
    brand: '테일러',
    title: '[테일러] 트리플 클렌즈 주스 24시간 946mL',
    desc: '세콤달콤',
    price: 12000,
    discount: 0,
    delivery: '샛별배송',
    reviews: 0,
    img: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&q=80&w=400', // 오렌지 주스 대체 이미지
  },
  {
    id: 2,
    brand: '롯데칠성',
    title: '[롯데칠성] 칠성사이다 제로 라임 (355mL X 6개)',
    desc: '톡 쏘는 청량함',
    price: 5980,
    discount: 0,
    delivery: '샛별배송',
    reviews: 0,
    img: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&q=80&w=400', // 캔 음료 대체 이미지
  },
  {
    id: 3,
    brand: '오후의 홍차',
    title: '[오후의 홍차] 차이티 라떼 400mL',
    desc: '일본에서 온 스파이시 한 겨울 음료',
    price: 3200, // 원가
    salePrice: 2600, // 할인가
    discount: 18,
    delivery: '샛별배송',
    reviews: 43,
    img: 'https://images.unsplash.com/photo-1596910547037-846b19803115?auto=format&fit=crop&q=80&w=400', // 밀크티 대체 이미지
  },
];

export const NAV_LINKS = [
  { label: '베스트', href: '/products?q=베스트' },
  { label: '세일', href: '/products?q=세일' },
  { label: '패션', href: '/products?q=패션' },
  { label: '리빙', href: '/products?q=리빙' },
  { label: '신상', href: '/products?q=신상' },
  { label: '특가/혜택', href: '/products?q=특가/혜택' },
];
