import {
  Apple,
  Baby,
  Brush,
  Coffee,
  Cookie,
  CookingPot,
  Croissant,
  Droplets,
  Drumstick,
  Fish,
  GlassWater,
  HeartPulse,
  Home,
  Leaf,
  Milk,
  PawPrint,
  Plug,
  Shirt,
  Sofa,
  Soup,
  Sparkles,
  SprayCan,
  Tent,
  Utensils,
  Wheat,
  Wine,
} from 'lucide-react';
import { CategoryType } from '../types';

export const CATEGORIES: CategoryType[] = [
  {
    id: '1',
    label: '채소',
    icon: Leaf,
    subcategories: [
      { id: '1', label: '전체보기' },
      { id: '27', label: '친환경' },
      { id: '28', label: '고구마·감자·당근' },
      { id: '29', label: '시금치·쌈채소·나물' },
      { id: '30', label: '브로콜리·파프리카·양배추' },
      { id: '31', label: '양파·대파·마늘·배추' },
      { id: '32', label: '오이·호박·고추' },
      { id: '33', label: '냉동·이색·간편채소' },
      { id: '34', label: '콩나물·버섯' },
    ],
  },
  {
    id: '2',
    label: '과일·견과·쌀',
    icon: Apple,
    subcategories: [
      { id: '2', label: '전체보기' },
      { id: '35', label: '친환경' },
      { id: '36', label: '제철과일' },
      { id: '37', label: '국산과일' },
      { id: '38', label: '수입과일' },
      { id: '39', label: '간편과일' },
      { id: '40', label: '냉동·건과일' },
      { id: '41', label: '견과류' },
      { id: '42', label: '쌀·잡곡' },
    ],
  },
  {
    id: '3',
    label: '수산·해산·건어물',
    icon: Fish,
    subcategories: [
      { id: '3', label: '전체보기' },
      { id: '43', label: '제철수산' },
      { id: '44', label: '생선류' },
      { id: '45', label: '굴비·반건류' },
      { id: '46', label: '연어·참치' },
      { id: '47', label: '회·탕류' },
      { id: '48', label: '오징어·낙지·문어' },
      { id: '49', label: '해산물·전복·조개류' },
      { id: '50', label: '새우·게·랍스터' },
      { id: '51', label: '수산가공품' },
      { id: '52', label: '명란' },
      { id: '53', label: '젓갈·장류' },
      { id: '54', label: '간편구이' },
      { id: '55', label: '김·미역·해조류' },
      { id: '56', label: '멸치·황태·다시팩' },
      { id: '57', label: '조미오징어·어포·쥐포' },
    ],
  },
  {
    id: '4',
    label: '정육·가공육·달걀',
    icon: Drumstick,
    subcategories: [
      { id: '4', label: '전체보기' },
      { id: '58', label: '국내산 소고기' },
      { id: '59', label: '수입산 소고기' },
      { id: '60', label: '국내산 돼지고기' },
      { id: '61', label: '수입산 돼지고기·양고기' },
      { id: '62', label: '닭·오리고기' },
      { id: '63', label: '식단관리용 가공육' },
      { id: '64', label: '양념육' },
      { id: '65', label: '돈까스·떡갈비·함박' },
      { id: '66', label: '소시지·베이컨·하몽' },
      { id: '67', label: '달걀·가공란' },
    ],
  },
  {
    id: '5',
    label: '국·반찬·메인요리',
    icon: Soup,
    subcategories: [
      { id: '5', label: '전체보기' },
      { id: '68', label: '국·탕·찌개' },
      { id: '69', label: '밑반찬' },
      { id: '70', label: '김치·젓갈·장류' },
      { id: '71', label: '두부·어묵·부침개' },
      { id: '72', label: '메인요리' },
    ],
  },
  {
    id: '6',
    label: '간편식·밀키트·샐러드',
    icon: CookingPot,
    subcategories: [
      { id: '6', label: '전체보기' },
      { id: '73', label: '밀키트' },
      { id: '74', label: '샐러드·샌드위치' },
      { id: '75', label: '선식·시리얼' },
      { id: '76', label: '도시락·밥류' },
      { id: '77', label: '짜장·짬뽕·파스타·면류' },
      { id: '78', label: '떡볶이·튀김·순대' },
      { id: '79', label: '치킨·피자·핫도그·만두' },
    ],
  },
  {
    id: '7',
    label: '면·양념·오일',
    icon: Wheat,
    subcategories: [
      { id: '7', label: '전체보기' },
      { id: '80', label: '라면' },
      { id: '81', label: '파스타·면류·조리용 떡' },
      { id: '82', label: '밀가루·가루·믹스' },
      { id: '83', label: '햄·통조림·병조림' },
      { id: '84', label: '죽·스프·카레' },
      { id: '85', label: '양념·액젓·장류' },
      { id: '86', label: '식용유·참기름·오일' },
      { id: '87', label: '식초·소스·드레싱' },
      { id: '88', label: '소금·설탕·향신료' },
      { id: '89', label: '조미료' },
      { id: '90', label: '면·양념·오일 선물세트' },
    ],
  },
  {
    id: '8',
    label: '생수·음료',
    icon: Droplets,
    subcategories: [
      { id: '8', label: '전체보기' },
      { id: '91', label: '생수/얼음' },
      { id: '92', label: '탄산수' },
      { id: '93', label: '탄산·스포츠음료' },
      { id: '94', label: '과일·야채음료' },
      { id: '95', label: '차음료' },
      { id: '96', label: '어린이음료·선물세트' },
    ],
  },
  {
    id: '9',
    label: '커피·차',
    icon: Coffee,
    subcategories: [
      { id: '9', label: '전체보기' },
      { id: '97', label: '원두커피' },
      { id: '98', label: '드립백/커피백' },
      { id: '99', label: '캡슐커피' },
      { id: '100', label: '콜드브루' },
      { id: '101', label: '커피음료' },
      { id: '102', label: '인스턴트 커피' },
      { id: '103', label: '곡물차/전통차' },
      { id: '104', label: '홍차/녹차/보이차' },
      { id: '105', label: '허브차/꽃차/과일차' },
      { id: '106', label: '코코아/밀크티/기타 차' },
      { id: '107', label: '액상차/청' },
      { id: '108', label: '커피/차 선물세트' },
    ],
  },
  {
    id: '10',
    label: '간식·과자·떡',
    icon: Cookie,
    subcategories: [
      { id: '10', label: '전체보기' },
      { id: '109', label: '과자·간식' },
      { id: '110', label: '쿠키·비스킷·크래커' },
      { id: '111', label: '초콜릿·젤리·캔디' },
      { id: '112', label: '유아 과자·간식' },
      { id: '113', label: '대용량 과자·간식' },
      { id: '114', label: '떡·한과' },
    ],
  },
  {
    id: '11',
    label: '베이커리',
    icon: Croissant,
    subcategories: [
      { id: '11', label: '전체보기' },
      { id: '115', label: '이 주의 추천 베이커리' },
      { id: '116', label: '식빵·모닝빵·베이글' },
      { id: '117', label: '간식빵' },
      { id: '118', label: '타르트·파이' },
      { id: '119', label: '디저트' },
      { id: '120', label: '케이크' },
      { id: '121', label: '잼·스프레드' },
    ],
  },
  {
    id: '12',
    label: '유제품',
    icon: Milk,
    subcategories: [
      { id: '12', label: '전체보기' },
      { id: '122', label: '우유·두유' },
      { id: '123', label: '요거트·생크림' },
      { id: '124', label: '자연치즈' },
      { id: '125', label: '가공치즈' },
      { id: '126', label: '버터' },
      { id: '127', label: '아이스크림' },
    ],
  },
  {
    id: '13',
    label: '건강식품',
    icon: HeartPulse,
    subcategories: [
      { id: '13', label: '전체보기' },
      { id: '128', label: '비타민·미네랄' },
      { id: '129', label: '건강즙·건강음료' },
      { id: '130', label: '홍삼·인삼' },
      { id: '131', label: '꿀·과일청' },
      { id: '132', label: '영양제' },
      { id: '133', label: '유산균' },
      { id: '134', label: '건강분말·건강환' },
      { id: '135', label: '체중관리' },
      { id: '136', label: '프로틴' },
      { id: '137', label: '이너뷰티' },
      { id: '138', label: '유아동·키즈' },
    ],
  },

  {
    id: '14',
    label: '와인·위스키·데낄라',
    icon: Wine,
    subcategories: [
      { id: '14', label: '전체보기' },
      { id: '139', label: 'CU BAR 픽업' },
      { id: '140', label: '라빈리커 픽업' },
      { id: '141', label: '와인앤모어 픽업' },
      { id: '142', label: '레드텅 와인샵 픽업' },
      { id: '143', label: '레드와인' },
      { id: '144', label: '화이트·로제와인' },
      { id: '145', label: '샴페인·스파클링' },
      { id: '146', label: '위스키·리큐르' },
      { id: '147', label: '사케' },
      { id: '148', label: '맥주·하이볼' },
      { id: '149', label: '스위트와인' },
      { id: '150', label: '고량주' },
      { id: '151', label: '데낄라' },
      { id: '152', label: '논알콜·무알콜' },
      { id: '153', label: '와인·위스키용품' },
    ],
  },
  {
    id: '15',
    label: '전통주',
    icon: GlassWater,
    subcategories: [
      { id: '15', label: '전체보기' },
      { id: '154', label: '막걸리·탁주' },
      { id: '155', label: '증류주·약주·청주' },
      { id: '156', label: '과실주·리큐르' },
      { id: '157', label: '라빈리커 픽업' },
      { id: '158', label: '전통주 선물세트' },
    ],
  },

  {
    id: '16',
    label: '패션',
    icon: Shirt,
    subcategories: [
      { id: '16', label: '전체보기' },
      { id: '159', label: '여성의류' },
      { id: '160', label: '언더웨어·라운지웨어' },
      { id: '161', label: '슈즈' },
      { id: '162', label: '가방·지갑' },
      { id: '163', label: '주얼리·액세서리' },
      { id: '164', label: '애슬레저·스윔웨어·스포츠' },
      { id: '165', label: '스카프·아이웨어·양말·소품' },
      { id: '166', label: '키즈패션' },
      { id: '167', label: '남성의류' },
      { id: '168', label: '명품' },
      { id: '169', label: 'Groom Only' },
      { id: '170', label: '구름배송' },
    ],
  },

  {
    id: '17',
    label: '주방용품',
    icon: Utensils,
    subcategories: [
      { id: '17', label: '전체보기' },
      { id: '171', label: '일회용품·주방잡화' },
      { id: '172', label: '주방·조리도구' },
      { id: '173', label: '냄비·팬·솥' },
      { id: '174', label: '식기·그릇' },
      { id: '175', label: '컵·잔·물병' },
      { id: '176', label: '밀폐·보관·저장용기' },
      { id: '177', label: '커트러리' },
      { id: '178', label: '주방수납정리' },
      { id: '179', label: '보관용기·텀블러' },
    ],
  },
  {
    id: '18',
    label: '생활용품·리빙',
    icon: Home,
    subcategories: [
      { id: '18', label: '전체보기' },
      { id: '180', label: '화장지·물티슈' },
      { id: '181', label: '세제' },
      { id: '182', label: '탈취·제습·방충제' },
      { id: '183', label: '청소용품' },
      { id: '184', label: '욕실용품' },
      { id: '185', label: '세탁용품' },
      { id: '186', label: '수납정리용품' },
      { id: '187', label: '의약외품·마스크' },
      { id: '188', label: '여성·위생용품' },
      { id: '189', label: '취미·문구·오피스' },
    ],
  },
  {
    id: '19',
    label: '가전제품',
    icon: Plug,
    subcategories: [
      { id: '19', label: '전체보기' },
      { id: '190', label: '생활가전' },
      { id: '191', label: '주방가전' },
      { id: '192', label: '계절가전' },
      { id: '193', label: '디지털·PC' },
      { id: '194', label: '대형·설치가전' },
    ],
  },
  {
    id: '20',
    label: '가구·인테리어',
    icon: Sofa,
    subcategories: [
      { id: '20', label: '전체보기' },
      { id: '195', label: '이불·베개·패드' },
      { id: '196', label: '침대·매트리스·토퍼' },
      { id: '197', label: '홈데코·조명·거울' },
      { id: '198', label: '홈패브릭' },
      { id: '199', label: '행거·옷장' },
      { id: '200', label: '테이블·식탁·책상' },
      { id: '201', label: '소파·의자' },
      { id: '202', label: '서랍·선반·진열장' },
      { id: '203', label: '화장대·콘솔' },
    ],
  },
  {
    id: '21',
    label: '유아동',
    icon: Baby,
    subcategories: [
      { id: '21', label: '전체보기' },
      { id: '204', label: '이유식 재료' },
      { id: '205', label: '분유·간편 이유식' },
      { id: '206', label: '간식·음식' },
      { id: '207', label: '건강식품' },
      { id: '208', label: '이유·수유용품' },
      { id: '209', label: '세제·위생용품' },
      { id: '210', label: '스킨·구강케어' },
      { id: '211', label: '완구·잡화류' },
      { id: '212', label: '유아동패션' },
      { id: '213', label: '기저귀·물티슈' },
    ],
  },
  {
    id: '22',
    label: '반려동물',
    icon: PawPrint,
    subcategories: [
      { id: '22', label: '전체보기' },
      { id: '214', label: '강아지 주식' },
      { id: '215', label: '강아지 간식·영양제' },
      { id: '216', label: '고양이 주식' },
      { id: '217', label: '고양이 간식·영양제' },
      { id: '218', label: '배변용품' },
      { id: '219', label: '미용·목욕용품' },
      { id: '220', label: '펫 의류·외출용품' },
      { id: '221', label: '급식기·급수기' },
      { id: '222', label: '하우스용품' },
      { id: '223', label: '장난감' },
    ],
  },
  {
    id: '23',
    label: '스포츠·레저·캠핑',
    icon: Tent,
    subcategories: [
      { id: '23', label: '전체보기' },
      { id: '224', label: '골프' },
      { id: '225', label: '휘트니스' },
      { id: '226', label: '캠핑' },
    ],
  },
  {
    id: '24',
    label: '스킨케어·메이크업',
    icon: Brush,
    subcategories: [
      { id: '24', label: '전체보기' },
      { id: '227', label: '스킨·미스트·패드' },
      { id: '228', label: '에센스·앰플·로션' },
      { id: '229', label: '크림·오일' },
      { id: '230', label: '클렌징' },
      { id: '231', label: '마스크팩' },
      { id: '232', label: '선케어' },
      { id: '233', label: '베이스메이크업' },
      { id: '234', label: '립메이크업' },
      { id: '235', label: '아이메이크업' },
      { id: '236', label: '맨즈케어' },
      { id: '237', label: '뷰티소품·기기' },
      { id: '238', label: '스킨케어세트' },
    ],
  },
  {
    id: '25',
    label: '헤어·바디·구강',
    icon: SprayCan,
    subcategories: [
      { id: '25', label: '전체보기' },
      { id: '239', label: '구강·면도' },
      { id: '240', label: '샴푸·컨디셔너' },
      { id: '241', label: '트리트먼트·팩' },
      { id: '242', label: '헤어에센스·염모' },
      { id: '243', label: '바디워시·스크럽' },
      { id: '244', label: '바디로션·크림' },
      { id: '245', label: '핸드·립·데오' },
      { id: '246', label: '향수·디퓨저' },
      { id: '247', label: '헤어·바디소품' },
      { id: '248', label: '헤어·바디·구강케어세트' },
    ],
  },
  {
    id: '26',
    label: '럭셔리뷰티',
    icon: Sparkles,
    subcategories: [
      { id: '26', label: '전체보기' },
      { id: '249', label: '스킨케어' },
      { id: '250', label: '메이크업' },
      { id: '251', label: '바디케어' },
      { id: '252', label: '헤어케어' },
      { id: '253', label: '프래그런스' },
      { id: '254', label: '클렌징' },
      { id: '255', label: '선케어' },
      { id: '256', label: '남성케어' },
    ],
  },
] as const;

export const SUB_CATEGORIES = [
  '생수/얼음',
  '탄산수',
  '탄산/스포츠음료',
  '과일야채음료',
  '차음료',
  '어린이음료/선물세트',
];

export const PRODUCTS = [
  {
    id: 1,
    brand: '테일러',
    title: '[테일러] 트리플 클렌즈 주스 24시간 946mL',
    desc: '세콤달콤',
    price: 12000,
    likes: 0,
    discount: 0,
    delivery: '샛별배송',
    reviews: 0,
    img: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&q=80&w=400', // 오렌지 주스 대체 이미지
  },
  {
    id: 2,
    brand: '롯데칠성',
    title: '[롯데칠성] 칠성사이다 제로 라임 (355mL X 6개)',
    desc: '톡 쏘는 청량함',
    price: 5980,
    likes: 0,
    discount: 0,
    delivery: '샛별배송',
    reviews: 0,
    img: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&q=80&w=400', // 캔 음료 대체 이미지
  },
  {
    id: 3,
    brand: '오후의 홍차',
    title: '[오후의 홍차] 차이티 라떼 400mL',
    desc: '일본에서 온 스파이시 한 겨울 음료',
    price: 3200, // 원가
    likes: 99,
    salePrice: 2600, // 할인가
    discount: 18,
    delivery: '샛별배송',
    reviews: 43,
    img: 'https://images.unsplash.com/photo-1596910547037-846b19803115?auto=format&fit=crop&q=80&w=400', // 밀크티 대체 이미지
  },
];

export const NAV_LINKS = [
  { label: '채소', href: '/categories/1' },
  { label: '과일', href: '/categories/2' },
  { label: '육류', href: '/categories/3' },
  { label: '해산물', href: '/categories/4' },
  { label: '건강식품', href: '/categories/5' },
  { label: '기타', href: '/categories/6' },
];

// export const NAV_LINKS = [
//   { label: '베스트', href: '/categories/1' },
//   { label: '세일', href: '/categories/2' },
//   { label: '패션', href: '/categories/3' },
//   { label: '리빙', href: '/categories/4' },
//   { label: '신상', href: '/categories/5' },
//   { label: '특가/혜택', href: '/categories/6' },
// ];
