import { HomeCategory } from '../types/model';

export const HOME_CATEGORY: HomeCategory[] = [
  {
    emoji: '🥬',
    title: '신선함이 다른 채소',
    subtitle: '오늘 수확한 듯한 신선 채소를 만나보세요',
    id: '1',
  },
  {
    emoji: '🍎',
    title: '자연의 달콤함 그대로',
    subtitle: '제철 과일·견과·쌀까지 한 번에',
    id: '2',
  },
  {
    emoji: '🐟',
    title: '바다의 신선함을 담다',
    subtitle: '매일 즐기는 수산·해산물',
    id: '3',
  },
  {
    emoji: '🥩',
    title: '믿고 먹는 정육',
    subtitle: '엄선한 고기와 달걀로 식탁 완성',
    id: '4',
  },
  {
    emoji: '🍲',
    title: '집밥이 쉬워지는 순간',
    subtitle: '국부터 메인요리까지 간편하게',
    id: '5',
  },
  {
    emoji: '🥗',
    title: '바쁜 하루를 위한 선택',
    subtitle: '간편식·밀키트로 완성하는 한 끼',
    id: '6',
  },
  {
    emoji: '🍜',
    title: '요리의 기본을 채우다',
    subtitle: '면·양념·오일까지 한 번에 준비',
    id: '7',
  },
  {
    emoji: '🥤',
    title: '갈증을 채우는 한 모금',
    subtitle: '매일 필요한 생수와 음료',
    id: '8',
  },
  {
    emoji: '☕️',
    title: '향으로 시작하는 하루',
    subtitle: '커피·차로 여유를 더해보세요',
    id: '9',
  },
  {
    emoji: '🍪',
    title: '당기는 순간의 행복',
    subtitle: '간식·과자로 소소한 즐거움',
    id: '10',
  },
  {
    emoji: '🥐',
    title: '갓 구운 듯한 행복',
    subtitle: '베이커리·디저트의 달콤함',
    id: '11',
  },
  {
    emoji: '🥛',
    title: '매일 챙기는 유제품',
    subtitle: '우유부터 아이스크림까지',
    id: '12',
  },
  {
    emoji: '💪',
    title: '건강을 챙기는 습관',
    subtitle: '하루 한 포로 시작하는 건강관리',
    id: '13',
  },
  {
    emoji: '🍷',
    title: '특별한 날을 위한 선택',
    subtitle: '와인·위스키로 완성하는 순간',
    id: '14',
  },
  {
    emoji: '🍶',
    title: '우리 술의 깊은 맛',
    subtitle: '전통주로 즐기는 색다른 풍미',
    id: '15',
  },
  {
    emoji: '👕',
    title: '스타일을 완성하다',
    subtitle: '일상부터 특별한 날까지',
    id: '16',
  },
  {
    emoji: '🍴',
    title: '주방의 모든 것',
    subtitle: '요리가 즐거워지는 주방용품',
    id: '17',
  },
  {
    emoji: '🧴',
    title: '생활을 더 편리하게',
    subtitle: '매일 쓰는 리빙 필수템',
    id: '18',
  },
  {
    emoji: '🔌',
    title: '생활을 스마트하게',
    subtitle: '집을 바꾸는 가전제품',
    id: '19',
  },
  {
    emoji: '🛋️',
    title: '공간의 분위기를 바꾸다',
    subtitle: '가구·인테리어로 완성하는 집',
    id: '20',
  },
  {
    emoji: '🍼',
    title: '아이를 위한 선택',
    subtitle: '유아동을 위한 안전한 상품',
    id: '21',
  },
  {
    emoji: '🐾',
    title: '반려동물의 하루',
    subtitle: '사랑하는 반려동물을 위한 용품',
    id: '22',
  },
  {
    emoji: '⛺️',
    title: '활동적인 일상',
    subtitle: '스포츠·레저·캠핑을 즐겨보세요',
    id: '23',
  },
  {
    emoji: '💄',
    title: '나를 가꾸는 시간',
    subtitle: '스킨케어·메이크업으로 완성',
    id: '24',
  },
  {
    emoji: '🫧',
    title: '매일의 케어 루틴',
    subtitle: '헤어·바디·구강까지 꼼꼼하게',
    id: '25',
  },
  {
    emoji: '✨',
    title: '격이 다른 아름다움',
    subtitle: '프리미엄 럭셔리 뷰티 컬렉션',
    id: '26',
  },
];
